#*****************************************#
# Chp 9 Debugging, condition handling, and 
# defensive programming 
#******************************************#

# Use functions e.g. traceback(), browser() to debugging
# conditions: errors, warnings, and messages

# fatal erros are raised by stop() and force to stop all execution
  # there's no way for a function to continue

# Warnings are generated by warning() 
  # display potential problem

# messages are generated by message()
  # used to give an informative output

## Condition handling tools : 
  # withCallingHandlers()
  # tryCatch()
  # try()



## defensive programming: 
  # ways to avoid common errors before they occur
  # 3 particular forms: 
    # checking inputs are correct
    # avoiding non-standard evaluation
    # avoiding functions that can return different types of output



#====================#
# 9.2 Debugging Tools
#====================#
# 3 KEY debugging tools:
  # traceback(): which list the seq of calls that lead to error
  # options(error = browser) opens an iteractive session where the error occured
  # 


f <- function(a) g(a)
g <- function(b) h(b)
h <- function(c) i(c)
i <- function(d) "a" + d
f(10)





























