#*==========================
#* Chp 9 Debugging, 
#* condition handling, 
#* definsive programming
#* ===============================
#* 
#* debugging: 
    # fix unanticipated problems
    # find the root cause of errors
    # traceback(), brower(), etc.

#* condition handling: 
    # functions can communicate problems
    # and how to take action based on these communications
    # communication problems to the users is the job of conditioning:
      # errors, warnings, messages

          # fatal errors: raised by stop() 
                        # and forces all execution to terminate
                        # used when there's no way for a function to continue
      
          # warnings: raised by warning()
                      # display potential problems
                      # e.g. some inputs are invalid
      
          # Messages: generated by messages()
                      # let the users know what you have done for a default arg

  # conditions are usually displayed in bold font or red

  # function authors can communicate with their users with print()
  # print output is NOT a condition

  # condition handling tools: 
      # tryCatch()
      # try()
    # take specific actions when condition occurs
   

#* denfensive programming: 
    # avoid common problems before they occur
    # principle: raise an error as soon as sth goes wrong
    # this takes 3 particular form:
        # checking inputs are correct
        # avoid non-standard evaluation
        # avoid functions that can return different types of output


#=========================
# 9.1 Debugging techniques
#=========================

# productively debug a problem with print()
# useful tools 
# outline a general procedure for debugging

# 4 steps:
  # realise you have a code
    # automated test for high quality of the paper

  # make it repeatable
    # once have a bug, be able to reproduce it on command
    # binary search, repeatedly remove half of the code
      # until you find the bug
    # if it takes a long time to generate the bug, 
      # also worthwhile to figure out how to generate it faster

  # figure where it is
  # figure it and test it
      # have automated test in place




















